# Generated by Django 4.2 on 2025-03-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('website_url', models.CharField(max_length=512)),
                ('website_hash', models.CharField(max_length=64)),
            ],
        ),
    ]
